Class {
	#name : #ToBarConfigurator,
	#superclass : #Object,
	#category : #'Toplo-Widget-List-Core-BarElement'
}

{ #category : #visiting }
ToBarConfigurator >> visitBarElement: aBarElement [

]

{ #category : #visiting }
ToBarConfigurator >> visitBarNode: aBarNode [

]

{ #category : #visiting }
ToBarConfigurator >> visitInnerBarElement: anInnerBarElement [

]

{ #category : #visiting }
ToBarConfigurator >> visitScrollableBarElement: aScrollableBarElement [

]

{ #category : #visiting }
ToBarConfigurator >> visitScrollableBarTrackElement: anScrollableBarTrackElement [

]
