Class {
	#name : #ToNoneSelectionModelSelecter,
	#superclass : #ToAbstractSelectionModelSelecter,
	#category : #'Toplo-Widget-List-Selection-Mode'
}

{ #category : #accessing }
ToNoneSelectionModelSelecter >> currentIndex [

	^ 0
]

{ #category : #operations }
ToNoneSelectionModelSelecter >> deselectAll [

]

{ #category : #operations }
ToNoneSelectionModelSelecter >> deselectAllIndexes: anArray [

]

{ #category : #operations }
ToNoneSelectionModelSelecter >> deselectIndex: anIndex [
]

{ #category : #operations }
ToNoneSelectionModelSelecter >> selectAll [
]

{ #category : #operations }
ToNoneSelectionModelSelecter >> selectAllIndexes: anArray [
]

{ #category : #operations }
ToNoneSelectionModelSelecter >> selectAndScrollToIndex: anIndex [


]

{ #category : #'shortcuts operations' }
ToNoneSelectionModelSelecter >> selectAndScrollToNext [
]

{ #category : #'shortcuts operations' }
ToNoneSelectionModelSelecter >> selectAndScrollToNextDeselected [
]

{ #category : #'shortcuts operations' }
ToNoneSelectionModelSelecter >> selectAndScrollToPrevious [
]

{ #category : #'shortcuts operations' }
ToNoneSelectionModelSelecter >> selectAndScrollToPreviousDeselected [
]

{ #category : #operations }
ToNoneSelectionModelSelecter >> selectIndex: anIndex [
]

{ #category : #operations }
ToNoneSelectionModelSelecter >> selectIndex: aStartIndex to: anEndIndex [
]

{ #category : #operations }
ToNoneSelectionModelSelecter >> selectOnlyIndex: anIndex [
]

{ #category : #operations }
ToNoneSelectionModelSelecter >> selectOnlyIndexes: anArray [
]

{ #category : #'shortcuts operations' }
ToNoneSelectionModelSelecter >> selectToIndex: index [
]
