Class {
	#name : #ToButtonLook,
	#superclass : #ToElementLook,
	#category : #'Toplo-Theme-Skins-Looks'
}

{ #category : #'event handling' }
ToButtonLook >> hoverStateEvent: anEvent [


]

{ #category : #'event handling' }
ToButtonLook >> initialStateEvent: anEvent [


]

{ #category : #'event handling' }
ToButtonLook >> installStateEvent: anEvent [


]

{ #category : #'event handling' }
ToButtonLook >> pressedStateEvent: anEvent [


]
