Class {
	#name : #ToPaneDresser,
	#superclass : #ToDresser,
	#category : #'Toplo-Widget-Pane'
}

{ #category : #'api - install/uninstall  hook' }
ToPaneDresser >> installEventListenersIn: anElement [

	super installEventListenersIn: anElement.
	
]

{ #category : #'api - install/uninstall  hook' }
ToPaneDresser >> uninstallEventListenersIn: anElement [

	super uninstallEventListenersIn: anElement.
	
	
	
]
